### ISSUE TITLE
In ClauseFeatureExtractor automatically populate pseudo-parse view? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#108]
In [ClauseFeatureExtractor](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/factory/ClauseFeatureExtractor.java#L49) we require pseudo-parse view, which seem to be created deterministically based on other views. It would be people's lives much easier if we check do it automatically, like how its done in the [unit test](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/edison/src/test/java/edu/illinois/cs/cogcomp/edison/features/factory/TestClauseFeatureExtractor.java#L59).

**Comment by danyaljj** [comment]
@mssammon I think I can do this.

**Comment by mssammon** [comment]
k -- I'll put it in the task table (am editing it now)

**Comment by danyaljj** [comment]
Not sure what I was thinking; now I think what the extractor does makes sense. In case the pseudo_parse is missing, one can manually add it using [the corresponding view generator](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/d62d0fd14f928263cc5a61385394a7a07d529c62/edison/src/main/java/edu/illinois/cs/cogcomp/edison/annotators/PseudoParse.java).
