### ISSUE TITLE
How to fix tokenizer issues? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#110]
Do we have a systematic way of fixing tokenizer issues? 
For this question I am getting: 
```
Input =  In New York State, the longest period of daylight occurs during which month?
Tokens = (In, New, York, State, ,, the, longest, period, of, daylight, occurs, during, which, month, ?)
```
At the very least we can have a file which contains the compound words that need to be together at the time of tokenization....

**Comment by mssammon** [comment]
Why is this tokenization incorrect?

**Comment by danyaljj** [comment]
Shouldn't "New York State" be one single token?

**Comment by christos-c** [comment]
I don't think so... That's what NER is for.

**Comment by danyaljj** [comment]
Pfff of course .....
