### ISSUE TITLE
CuratorFactoryTest

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#12]
Follow up on this: https://github.com/cogcomp-dev/illinois-cogcomp-nlp/issues/35 

[`CuratorFactoryTest`](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/curator/src/test/java/edu/illinois/cs/cogcomp/curator/CuratorFactoryTest.java) has some issues on the CI at some point and it was failing so it was commented. Maybe we should address it again:

**Comment by christos-c** [comment]
Fixed in #57
