### ISSUE TITLE
WordConjunctionOneTwoThreeGramWindowTwo causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mliu-dark-knight** [IllinoisCogComp/illinois-cogcomp-nlp#129]
`WordConjunctionOneTwoThreeGramWindowTwo` causes `ArrayIndexOutOfBoundsException`.  The following code can be used to reproduce the issue:

```java
WordConjunctionOneTwoThreeGramWindowTwo wordconj = new WordConjunctionOneTwoThreeGramWindowTwo("WordConj3GramWin2");
TextAnnotation ta = TextAnnotationUtilities.createFromTokenizedString("I give John $900 today .");
Constituent c = ta.getView(ViewNames.TOKENS).getConstituentsCoveringSpan(3, 4).get(0);
wordconj.getFeatures(c);
```
Error caused by line 71 in `WordConjunctionOneTwoThreeGramWindowTwo`. Looks like `PosWordConjunctionSizeTwoWindowSizeTwo` have the same problem.

**Comment by christos-c** [comment]
Thanks @mliu-dark-knight. I'm fixing this instance, but @mssammon @danyaljj be aware that the existing unit tests missed this (never tried to extract features from > 2 index).
