### ISSUE TITLE
redundant readers? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#132]
Seems like these two files are doing the same thing? 
https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/ner/src/main/java/edu/illinois/cs/cogcomp/ner/ParsingProcessingData/ColumnFileReader.java
https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/nlp/corpusreaders/CoNLLColumnFormatReader.java

**Comment by mayhewsw** [comment]
They're not doing the same thing: the one from illinois-ner reads Conll column format (NER) into an NERDocument, not a TextAnnotation.

The corpusreaders one reads SRL format (I think) into a TextAnnotation.

**Comment by danyaljj** [comment]
@mayhewsw shouldn't this be assigned to Soham?

**Comment by danyaljj** [comment]
oops nvm.

**Comment by danyaljj** [comment]
Deemed invalid. Closing ....
