### ISSUE TITLE
Location for corpus writers

### ISSUE THREAD

**Issue by mayhewsw** [IllinoisCogComp/illinois-cogcomp-nlp#138]
We have a corpusreaders submodule, but I sometimes also want to write to CoNLL NER format from TextAnnotation. Where should this code go? It seems appropriate to put it in the corpusreaders directory, but it's not exactly a reader. 

My vote is to interpret "reader" liberally, as in, "corpus interaction" and include writers in the same directory.

**Comment by mssammon** [comment]
sounds good to me.
