### ISSUE TITLE
inconsistent behavior in TextAnnotation.getTokenIdFromCharacterOffset()

### ISSUE THREAD

**Issue by mssammon** [IllinoisCogComp/illinois-cogcomp-nlp#147]
If the last character offset in the text is used as an argument to this method, TextAnnotation returns one-past-the-end token index; this is  inconsistent with the method's behavior for any other index. Change to return the correct final token index.

**Comment by cogcomp-dev** [comment]
please also write a relevant test.

**Comment by mssammon** [comment]
@tkao1000 any questions about this?

**Comment by tofuwen** [comment]
I did test like this:

@Test
    public void test() {
        // The construction of the John Smith library finished on time .
        TextAnnotation ta = DummyTextAnnotationGenerator.generateAnnotatedTextAnnotation(false, 1);
        System.out.println(ta);
        System.out.println(ta.getTokenIdFromCharacterOffset(54)); // the white space before "time"
        System.out.println(ta.getTokenIdFromCharacterOffset(60)); // .
        System.out.println(ta.getTokenIdFromCharacterOffset(61)); // whitespace after .
        // sentence length == 62
        // return the number of tokens + 1, as commented in the TextAnnotation.getTokenIdFromCharacter
        System.out.println(ta.getTokenIdFromCharacterOffset(62));
    }

And got the desired behavior. 

The "one-past-the-end token index" will occur when you pass the parameter as the length of the sentence, but I think that's what we want, since in the TextAnnotation.getTokenIdFromCharacterOffset, here is the comment for this:

        // If the characterOffset is the number of characters (and hence doesn't
        // correspond to any character with a zero indexed scheme), return the
        // number of tokens + 1.
        if (characterOffset == characterOffsetsToTokens.length) {
            return this.size();
        }
I think this is what you mean here.

**Comment by mssammon** [comment]
This is good so far: please modify it so that instead of ```System.out``` you use ```assertEquals( <expectedValue>, ta.getTokenIdFrom...())```
Also, please check for other methods in TextAnnotation, View, and Constituent that use this method and make sure their behavior is as expected.

**Comment by tofuwen** [comment]
No problem.
I commented here since I don't think I get inconsistent behaviors.
I will check other methods as well.
