### ISSUE TITLE
ParsePhraseTypeOnlyTest fails on mac 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#152]
ParsePhraseTypeOnlyTest fails for me on my Macbook. 
As usual, might be a `Set` issue in Linux vs Mac

**Comment by shatu** [comment]
edu.illinois.cs.cogcomp.edison.features.factory.ParsePhraseTypeOnlyTest works on my mac.

**Comment by danyaljj** [comment]
Will try again on my machine.

**Comment by danyaljj** [comment]
What is your jvm version btw?

**Comment by danyaljj** [comment]
So when I run ` mvn -pl edison test`, I get: 
```
Results :

Failed tests:   testParsePhraseCharniak(edu.illinois.cs.cogcomp.edison.features.factory.ParsePhraseTypeOnlyTest): expected:<[[N]P]> but was:<[[P]P]>
  testParsePhraseStanford(edu.illinois.cs.cogcomp.edison.features.factory.ParsePhraseTypeOnlyTest): expected:<[[N]P]> but was:<[[P]P]>
  testParsePhraseGold(edu.illinois.cs.cogcomp.edison.features.factory.ParsePhraseTypeOnlyTest): expected:<[[N]P]> but was:<[[P]P]>

Tests run: 102, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by shatu** [comment]
From the command line, it gives me the same error. Although, when I run it from my eclipse, it works! Strange?

I'm using 1.7 btw.

**Comment by danyaljj** [comment]
Ignore eclipse. Commandline matters. 

here is what I think.  `stanford.getFeatures(.)`  returns a set, and when it gets converted to string, it gets different ordering, on different operating systems. 
My suggestion is, convert the set to an ordered sequence and sort it (say based on its characters), before converting it to string.

**Comment by shatu** [comment]
What's our target JVM?

**Comment by shatu** [comment]
Can this issue be closed now?
