### ISSUE TITLE
Understanding the parse view

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#154]
I'm trying to understand the parse view; need your help @christos-c @mssammon 

So when I do:
```
private static TextAnnotation tas = DummyTextAnnotationGenerator.generateAnnotatedTextAnnotation(false, 1);
private List<Constituent> cons = tas.getView(ViewNames.PARSE_GOLD).getConstituents();
System.out.println(cons.size());
System.out.println(cons);
System.out.println(tas.getView(ViewNames.PARSE_GOLD));
```

I see that: 
```
31
[The construction of the John Smith library finished on time ., The construction of the John Smith library finished on time ., The construction of the John Smith library, The construction, The, The, construction, construction, of the John Smith library, of, of, the John Smith library, the, the, John, John, Smith, Smith, library, library, finished on time, finished, finished, on time, on, on, time, time, time, ., .]
(S1 (S (NP (NP (DT The)
    (NN construction))
    (PP (IN of)
        (NP (DT the)
            (NNP John)
            (NNP Smith)
            (NN library))))
   (VP (VBD finished)
       (PP (IN on)
           (NP (NN time))))
   (. .)))
```

What confuses me is the existence of repeated spans among the constituents, for example `The` appear twice. (Similarly  `Smith`, or `finished`).
Is it reasonable?

**Comment by mssammon** [comment]
Yes. Think about each pair of parenthesis and the words that are covered by that span (the yield of that internal node in the tree).  Each entry in the list in square brackets corresponds to the yield of a span. The word 'The' is covered by a DT, a NP ("The construction"), another NP ( "The Construction of the John Smith Library"), and an S. Each leaf node parent corresponds to a part of speech, and the leaf node itself is the actual word, so you get "The" as an internal node with the label "DT" and also as a word.

**Comment by danyaljj** [comment]
Ah I see each leaf node is repeated twice ...
