### ISSUE TITLE
Documentation: How to install ner models?

### ISSUE THREAD

**Issue by borice** [IllinoisCogComp/illinois-cogcomp-nlp#158]
There is no info on how to install the NER models after downloading "Illinois Named Entity Tagger (3.0.23) ". There is a script `scripts/maven-models.sh` but it's not clear what arguments you have to pass (specifically, what VERSION of the models should be used).  Also, in `line 28` of the script, the host `bilbo.cs.uiuc.edu` is incorrect and should probably be `bilbo.cs.illinois.edu`.

**Comment by danyaljj** [comment]
You shouldn't need to look at that script. See a sample usage in this test file: https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/ner/src/test/java/edu/illinois/cs/cogcomp/ner/NerTest.java

**Comment by borice** [comment]
Ok, I was trying to follow the instructions in the README that say mention the use of the following command to annotate a set of plain-text documents:

`java -Xmx3g -classpath "dist/*:lib/*:models/*" edu.illinois.cs.cogcomp.ner.NerTagger -annotate input output config/ner.properties"`

The command seems to need the `models/*` folder, which I don't have based on the ZIP file I downloaded for version 3.0.23. Should I just ignore that folder? If not, where do I download the models from?

Thank you.

**Comment by danyaljj** [comment]
Depends on your usage. If you use maven (which suggest you do) the [models will be loaded automatically](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/ner/pom.xml#L52-L70).

**Comment by mayhewsw** [comment]
If you don't use maven, you may be able to [download the model file as a jar](http://cogcomp.cs.illinois.edu/m2repo/edu/illinois/cs/cogcomp/illinois-ner-model/3.2/), and put it in the lib/ directory.

**Comment by borice** [comment]
Thanks, @mayhewsw - that was what I was looking for.
