### ISSUE TITLE
NER programmatic usage

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#159]
@cowchipkid I think[ the programmatic usage of NER](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/tree/master/ner#programmatic-use) needs a little more detail. 
Like a user should be able to apply it on a raw text and get some labels in the output. Maybe make it more detailed? (or refer to the usages in the [tests](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/ner/src/test/java/edu/illinois/cs/cogcomp/ner/NerTest.java)?)

Related to #158 as well.

**Comment by cowchipkid** [comment]
@mayhewsw The edu.illinois.cs.cogcomp.ner.Main class is the entry point for the principle NER command line UI. This class is well documented from a JavaDoc perspective, but the overall menu hierachy is not documented even within the code unfortunately. I think we should replace the documentation of the edu.illinois.cs.cogcomp.ner.NerTagger with documentation on this more intuitive interactive app. Or we could document both. Any questions on this app, just ask.

**Comment by mayhewsw** [comment]
I spent time working through this today, and the result is [this blog post](http://mayhewsw.github.io/2016/09/14/illinois-ner-mvn/). This will be merged into the readme in order to close this PR.

It took me forever to find that Annotator class uses lazy initialization...

**Comment by cogcomp-dev** [comment]
@sdan2 please note this -- it overlaps with what you are working on.  @mayhewsw sorry that's my fault -- gave a detailed PR but didn't update the docs.
