### ISSUE TITLE
Redundancies in WN helpers? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#16]
Same as : https://github.com/cogcomp-dev/illinois-cogcomp-nlp/issues/56 
Seems like these files have a lot in common. Maybe they should be merged/combined into one single file? 

[files1](https://github.com/cogcomp-dev/illinois-cogcomp-nlp/blob/bc9f5836162fdf0af9b005a3e836071ff09786a2/edison/src/main/java/edu/illinois/cs/cogcomp/edison/utilities/WordNetHelper.java)
[filew2](https://github.com/cogcomp-dev/illinois-cogcomp-nlp/blob/bfd8c0f1a6fb3d1374a42b6ba7a5225fd569ffe2/edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/helpers/WordHelpers.java)

Relevant: 
[WordNetManager](https://github.com/cogcomp-dev/illinois-cogcomp-nlp/blob/bc9f5836162fdf0af9b005a3e836071ff09786a2/edison/src/main/java/edu/illinois/cs/cogcomp/edison/utilities/WordNetManager.java)

**Comment by Kevin5025** [comment]
Hello, I am not able to follow the links as they give me a 404.

**Comment by danyaljj** [comment]
Nvm this issue. Very old. I don't think it's relevant anymore.
