### ISSUE TITLE
tagger field null even if lazy initialization is disabled

### ISSUE THREAD

**Issue by reckart** [IllinoisCogComp/illinois-cogcomp-nlp#166]
The tagger field in the POSAnnotator remains null after instantiation even if lazy loading is disabled.

Debugging the problem, it seems to turn out that the [field initialization (tagger = null)](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/commit/6fde90746acba74c7f614ae9d7e39f1c7d79dbbf#diff-0dc695635998a8b8b2a7486515d0c422L39) is executed by the JVM **after** the initialize() method has been invoked (i.e. after the constructor call is complete).

**Comment by mssammon** [comment]
Good catch -- thanks.
