### ISSUE TITLE
Ability to retrieve possible tags from annotators

### ISSUE THREAD

**Issue by reckart** [IllinoisCogComp/illinois-cogcomp-nlp#167]
It would be nice if all the POSAnnotator, ChunkerAnnotator, NERAnnotator, etc. classes had a method that returns the tag values that these classes (or the respective loaded models) do produce. 

If lazy loading is enabled, an attempt to retrieve the tagset should trigger a loading of the model (at least those parts of it that contain the tagset information).

Right now, I have to extract the tagset information through reflection...

**Comment by cogcomp-dev** [comment]
@tofuwen please just do this for POS to start with.

**Comment by cogcomp-dev** [comment]
programmatically provide tag set via Annotator class interface. Implement default in Annotator
(empty tag set, warning "not yet implemented") and override in pos annotator subclass,
return set of  strings corresponding to tags.
Do this for relations also. (will be empty set for many NLP modules).
