### ISSUE TITLE
Default NER parameters

### ISSUE THREAD

**Issue by cowchipkid** [IllinoisCogComp/illinois-cogcomp-nlp#172]
The parameters to the SparseAveragedPerceptron employed by NER (hard coded in the LBJava file) are .1 for learning rate and 10 for thickness. Better choice for default would be .05 and 30.

**Comment by cogcomp-dev** [comment]
Xiaodong will be assigned this issue once he is in the cogcomp github group

**Comment by cowchipkid** [comment]
@yxd126 this issue requires not only that the defaults for both level 1 and 2 classifiers in the LBJava file are changed, but also that that lbjava file get recompiled, and the generated files need to be replaced. This is counterintuitive, so just thought it worth mentioning.

**Comment by cowchipkid** [comment]
I have added 4 config properties, "minConfidencePredictionsLevel1", "minConfidencePredictionsLevel2", "learningRatePredictionsLevel1", and "learningRatePredictionsLevel2", and have set the defaults to the best overall arguments from an extensive parameter sweep. We can also now do parameter sweeps by doing multiple configs in the benchmark tests each with different parameters set up.
