### ISSUE TITLE
Add publications to NLP tool READMEs

### ISSUE THREAD

**Issue by cogcomp-dev** [IllinoisCogComp/illinois-cogcomp-nlp#177]
Add a citation and pointer to the CCG web site for the relevant paper(s). These should be listed already on the relevant software package/demo page on the CCG web site.

**Comment by cogcomp-dev** [comment]
assigned to Menxiong; need github id

**Comment by danyaljj** [comment]
I have asked @mliu-dark-knight to add his name to his github account.

**Comment by mssammon** [comment]
Kevin will be assigned this ticket once he is a member of the cogcomp github group

**Comment by mssammon** [comment]
@Kevin5025 how is this going? Any problems?
