### ISSUE TITLE
Suggestion: make the java version, module specific 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#180]
Currently we have defined the java version in the[ root pom](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/pom.xml#L69-L70). 

It turns out that the[ java version can be set per module.](https://gist.github.com/aslakknutsen/9648594). So the suggestion is to move this version number inside each module. This will let the module that require jdk8 be included in the project (example, [big-data-utils](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/pull/119)).

**Comment by mssammon** [comment]
Alternatively, we could just agree to move to Java 8.  For a while we were somewhat constrained because DEFT partners were insisting everything be Java 7 or earlier, but I believe this constraint has now been lifted.

**Comment by danyaljj** [comment]
In that case we need to decide whether we want to restrict ourselves to jdk7 syntax or not. Personally I have not used the new syntax, but small samples that I have seen were not pretty.

**Comment by mssammon** [comment]
I don't think we can ask people to use 8 and restrict to 7 syntax. Sounds like a topic for the software group this week.

**Comment by danyaljj** [comment]
@mssammon we agreed on moving on to jdk8; right? Just wanted to make sure before sending any PR.

**Comment by mssammon** [comment]
yes, we are go for Java 8
