### ISSUE TITLE
Overrride default configurator for POS tagger

### ISSUE THREAD

**Issue by mayhewsw** [IllinoisCogComp/illinois-cogcomp-nlp#183]
There is no option to input a config file for the POS tagger. In order for a new user to specify a new training directory, you have to change POSConfigurator and recompile.

**Comment by b29308188** [comment]
@mssammon Should we also modify the main function in order for a new user to specify a new training directory?

**Comment by mssammon** [comment]
main() in which class?

**Comment by b29308188** [comment]
POSTrain

**Comment by mssammon** [comment]
Yes, I think that's a good idea.  It might be best to pass a config file and use it with PosConfigurator supplying default values.  Also, init() should be using constants from POSConfigurator, not string keys, when it gets values from the resourcemanager.

**Comment by b29308188** [comment]
I don't quite understand how to use constant from POSConfigurator.
If we want to use the constructor in ResourceManager : **public ResourceManager(String configFile_)**, then we must provide it with the string name in our configuration file.

For example,
trainingData = /shared/corpora/corporaWeb/written/eng/POS/00-18.br
devData = /shared/corpora/corporaWeb/written/eng/POS/19-21.br
testData = /shared/corpora/corporaWeb/written/eng/POS/22-24.br

may need to take the string names as input.

**Comment by mssammon** [comment]
The POSConfigurator and the keys in the config file must agree. If they don't already, one or the other needs to change. If entries are missing from the POSConfigurator, please add them.
