### ISSUE TITLE
Units tests for `TestParseFeatures`

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#19]
There are some [demonstrative tests for `TestParseFeatures` here](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/edison/src/test/java/edu/illinois/cs/cogcomp/edison/features/factory/TestParseFeatures.java). I think they should be converted to Unit-Tests.

**Comment by danyaljj** [comment]
Link updated.

**Comment by mpavankumarreddy** [comment]
@danyaljj - Close this issue now (Pull request already merged)?
