### ISSUE TITLE
Release updated chunker

### ISSUE THREAD

**Issue by mssammon** [IllinoisCogComp/illinois-cogcomp-nlp#211]
i.e. the download here: http://cogcomp.cs.illinois.edu/page/software_view/Chunker

make sure the correct models are deployed (deploy new ones to maven if necessary)
run the local test to make sure it behaves as expected.

**Comment by mssammon** [comment]
Generate a zip that contains the models, dependencies, 
and chunker jars. There should be a test run from the command line that annotates
a specific text file and compares the output to a reference output file.  For an example, look at the ner version: 
https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/ner/scripts/test-linux.sh

**Comment by qiangning** [comment]
Hi Mark, I need to upload (deploy) my new model (.lc/.lex) to our repo: http://cogcomp.cs.illinois.edu/m2repo/edu/illinois/cs/cogcomp/illinois-chunker-model/. What's the standard thing I need to do next?

**Comment by qiangning** [comment]
@mssammon One thing about the `release.sh`. My desktop cannot run it directly since my bash doesn't accept `function` in [L9](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/ner/scripts/release.sh#L9) and `[[` in [L50](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/ner/scripts/release.sh#L50). I had to change L9 to `HELP()` and I also ignored the error in L50.

**Comment by danyaljj** [comment]
Can u try 'bash release.sh'?

**Comment by danyaljj** [comment]
Or 'sh release.sh'?

**Comment by danr-ccg** [comment]
Hi,

I was planning to respond a few days ago but only now got it: are we talking here about the addition of the Brown Cluster features that Qiang added to the Chunker, or is this the old version?
Either way, it would be good to record results and compare to published ones; I have not seen numbers on this for some time.

Thanks,
              Dan

**Comment by qiangning** [comment]
Hi Dan. No, this is the version without `brown clustering`. 

Recently we had some updates for chunker on github (adding `brown cluster` will be a future update I guess), so I thought this one was simply packaging our github chunker so that we can publish it on our group website, whose chunker version was quite old.

**Comment by qiangning** [comment]
Hi Mark. In terms of the test run, what's the difference between what you suggested and `mvn test`? Is `mvn test` running the scripts in `src/test`? If yes, I didn't see a main function in `src/test`, how does it run?

**Comment by mssammon** [comment]
The test I mean is: given the distribution (dependencies in lib/, main jar in dist/, etc.) run a script from the command line that processes a short input text file and generates an annotated text file, and compares (e.g. diffs) the genrated output with a reference file, and reports the result (i.e ."TEST PASSED" or "TEST FAILED".  I linked to an example in the original issue post.

**Comment by mssammon** [comment]
@qiangning please hold off on actually putting the new tarball on the web site; #252 needs to be completed first

**Comment by qiangning** [comment]
Hi Mark, I have already finished packaging it. Maybe we can upload it while working on #252?

**Comment by mssammon** [comment]
I figured if we were going to make changes that affect the downloadable package we should wait rather than have to update the package a second time very quickly.  But thinking about it, #252 can be separate and shouldn't significantly affect the download package.

**Comment by qiangning** [comment]
Hi Mark, the updated chunker package can be found at /home/qning2/test/illinois-chunker.zip. Compared to my latest pull request, I include both maven scripts and java scripts. in `scripts/`, which should work as-is.

**Comment by mssammon** [comment]
@qiangning the new chunker runs as intended. I updated the corresponding package/web page.
