### ISSUE TITLE
junits in different modules 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#217]
Seems like each module has its own junit, with different version: 
https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/search?l=maven-pom&q=junit+&utf8=%E2%9C%93

I would suggestion unifying these. Potentially bringing them to the model `pom.xml`, so that all the modules inherit them.

**Comment by mssammon** [comment]
@mpavankumarreddy is this closed by #264?

**Comment by danyaljj** [comment]
Not addressed yet. I think we can drop all, and keep the one in core-utils. Should be an easy change ...

**Comment by danyaljj** [comment]
Not very important. Closing it.
