### ISSUE TITLE
junit 3 vs 4 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#218]
Many of the current test are written following junit 3 style (e.g. extending `TestCase`). 
I think we should move on to junit 4. 

Here is a brief comparison in syntax:  http://www.asjava.com/junit/junit-3-vs-junit-4-comparison/

**Comment by mssammon** [comment]
@mpavankumarreddy please work through the modules in order. If there are a lot of changes, let me know and I'll split this into smaller tasks.

**Comment by danyaljj** [comment]
@mpavankumarreddy are you planning to address this?

**Comment by mpavankumarreddy** [comment]
@danyaljj issued a pull request #264. Mostly adding @Test annotations and slight modifications. Can you review it and let me know if any changes are required.
