### ISSUE TITLE
Fix Chunker evaluation

### ISSUE THREAD

**Issue by mssammon** [IllinoisCogComp/illinois-cogcomp-nlp#222]
Fix/streamline testing scripts. Identify the source of variation, and either verify that different performance results are within expected bounds or identify a problem. @qiangning @b29308188  this follows on directly from your recent work on evaluating the Chunker.

**Comment by b29308188** [comment]
@mssammon  [Here](https://github.com/b29308188/illinois-cogcomp-nlp/blob/stable/chunker/src/main/java/edu/illinois/cs/cogcomp/chunker/main/LCTester.java) is my tester.  I have run it several times, but it gave the same results as I wrote in [wiki](https://wiki.illinois.edu/wiki/pages/viewpage.action?spaceKey=ccg&title=Chunker+Benchmark+Results).

**Comment by mssammon** [comment]
@b29308188 @qiangning once you determine the final official eval scripts, please talk with @cowchipkid about correct eval procedure/data splits.

**Comment by qiangning** [comment]
Hi Mark @mssammon, Ben @b29308188 and I just had a brief meeting regarding this problem. I realized that Ben was not aware of this [issue](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/issues/214). He has fixed this and re-generated his results, which are exactly the same as mine. I have also noted this in our [wiki](https://wiki.illinois.edu/wiki/display/ccg/Chunker+Benchmark+Results). I would suggest a closure for this issue.

**Comment by danyaljj** [comment]
Closed by #233
