### ISSUE TITLE
Verify and document NER benchmark. 

### ISSUE THREAD

**Issue by mssammon** [IllinoisCogComp/illinois-cogcomp-nlp#225]
Determine that performance is reproducible -- make sure correct process is clearly documented in the ner README.md. Fix the relevant code/scripts or remove classes/scripts if they are not needed.

**Comment by cowchipkid** [comment]
The interactive command line application is not the recommended approach, I added a section on this, and this is the application that is invoked when you run runNER.sh. Documentations is updated, but there is still information on running the older tagger command line.
