### ISSUE TITLE
NerAnnotatorManager warning is unclear

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#24]
Creating on behalf of @mssammon : 
Same as: https://github.com/cogcomp-dev/illinois-cogcomp-nlp/issues/145

in buildNerAnnotator(), if a user tries to replace an existing model/viewname pair, there is a warning that suggests the replacement happens but it does not

**Comment by mssammon** [comment]
I think this is incorrect, and may have been due to double-initialization in a test.
