### ISSUE TITLE
How to convert records to text annotation? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#248]
@mssammon I remember we had something to convert records to text annotation. Could you remember where it is? 

FYI @mpavankumarreddy

**Comment by mssammon** [comment]
@danyaljj did you find the code?

**Comment by danyaljj** [comment]
Nope, but Pavan said he asked you and you didn't know. 
I remember had sth somewhere, but don't remember now where it was. I remember Xiao told me about it, but don't remember it now.

**Comment by shatu** [comment]
I'm doing something similar here -- https://gitlab-beta.engr.illinois.edu/sgupta96/datalessclassification/blob/shashank/src/edu/illinois/cs/cogcomp/classification/representation/esa/entity/indexer/WikifiedWikiDocIndexer.java#L250

And according to @mpavankumarreddy, the aforementioned code snippet helps.

**Comment by mssammon** [comment]
This should specifically deal with it:
https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/curator/src/main/java/edu/illinois/cs/cogcomp/curator/CuratorDataStructureInterface.java
