### ISSUE TITLE
check Chunker training behavior

### ISSUE THREAD

**Issue by mssammon** [IllinoisCogComp/illinois-cogcomp-nlp#252]
make sure chunker training uses train and dev sets correctly.

**Comment by qiangning** [comment]
Hi Mark, I didn't know there's a dev set for chunker.

**Comment by mssammon** [comment]
if there isn't, we should create one...

**Comment by qiangning** [comment]
Hi Mark. If we want to have a dev set and let the chunker decide how many iterations it needs depending on its performance on dev set, we will need fix #214 first. I guess this could be a non-trivial task and may take some time?

**Comment by mssammon** [comment]
@qiangning you are right that #214 may require significant effort.  So go ahead and finalize this; I expect that addressing #214 will have minimal impact on the models, and re-releasing with updated code jars should be easy with the changes you are making for this issue.
