### ISSUE TITLE
NerAnnotatorManager not thread safe

### ISSUE THREAD

**Issue by cowchipkid** [IllinoisCogComp/illinois-cogcomp-nlp#254]
There were no synchronizations in the buildNerAnnotator method, this could result in the NERAnnotator being instantiated many times when the expected outcome was it should be instantiated once and reused.

**Comment by mssammon** [comment]
@cowchipkid was this addressed in the NER pull request we just merged?

**Comment by cowchipkid** [comment]
Yes, that is fixed.
