### ISSUE TITLE
update ACEReader to use StatefulTokenizer; possibly, make ST hyphen behavior configurable

### ISSUE THREAD

**Issue by mssammon** [IllinoisCogComp/illinois-cogcomp-nlp#257]
Currently this would cause a test to fail based on different behaviors w.r.t. hyphens. Generally, though, we are confident that StatefulTokenizer is more robust than IllinoisTokenizer, and the hyphen behavior is something of an arbitrary choice.  If appropriate, this may require the tokenizer to be modified to allow users to choose the hyphen-related split behavior.

**Comment by b29308188** [comment]
@mssammon I changed the IllinoisTokenizer into StatefulTokenizer.
But there's one test fails -- test2005Dataset.

In the assertion of this [file](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/corpusreaders/src/test/resources/edu/illinois/cs/cogcomp/nlp/corpusreaders/ace2005/timex2norm/XIN_ENG_20030616.0274.apf.xml) , it 
Expected :"Director - General", But Found:"Director-General".

**Comment by mssammon** [comment]
@cowchipkid I think we discussed hyphenation before -- can we add an option to StatefulTokenizer to allow the user to specify which hyphen splitting behavior it adopts?

**Comment by cowchipkid** [comment]
Do you have a particular fork you would like me to integrate this with, or do you want me to drop it into my fork?

**Comment by b29308188** [comment]
@cowchipkid I only updated ACEReader to use StatefulTokenizer but not modify the  behavior of the StatefulTokenizer. Do you make it allow the user to specify behaviors?

**Comment by cowchipkid** [comment]
@b29308188, Yes, I did (but doubt it is merged yet). There is a boolean argument to a new constructor, that argument will set up the tokenizer to split on "-" or not. In that same PR, I also modified the instantiation of StatefulTokenizer to appropriately set up that argument.

**Comment by mssammon** [comment]
@b29308188 I merged the PR with the hyphenation fix for tokenizer.  It should now be available to address this issue.

**Comment by mssammon** [comment]
@b29308188 any questions about this?

**Comment by b29308188** [comment]
@mssammom No. 
I am traveling internationally this days, and will be back to USA tomorrow and push my code. 
Sorry for the delay.

**Comment by mssammon** [comment]
Great -- thanks.

**Comment by b29308188** [comment]
@mssammon I think this issue is already solved in [this commit](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/commit/4ab374c7ba8cf82ac6d6bbb76409c945a571ce33). The tokenizer was changed to  StatefulTokenizer in the ACEReader, and there's an argument in the contrusctor of the StatefulTokenizer to decide whether to split with "-". (Although we say that '-" is the dash in the comments, it's actually an hyphen)

**Comment by mssammon** [comment]
closing....
