### ISSUE TITLE
updated edison to use new separated resources 

### ISSUE THREAD

**Issue by mssammon** [IllinoisCogComp/illinois-cogcomp-nlp#265]
previously everything was in illinois-common-resources.  We now have a group of jars for individual resources instead; update edison to use only those dependencies it needs.  Make sure there is some easily-found documentation that lists all these resources.

**Comment by danyaljj** [comment]
I think it's already done? 
https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/edison/pom.xml#L20-L79

**Comment by mssammon** [comment]
looks like you're right -- I saw the dependency was still there in a PR (it appeared to be causing a CI build fail), but I guess it must be an out-of-date branch.
@shatu, please point me to documentation for the new dependencies (is there a project for them? Maybe create an illinois-common-resources project that is just a pom containing all the dependencies, and a README that says where they are?)

**Comment by shatu** [comment]
#268

**Comment by shatu** [comment]
@mssammon .. Currently, there is no such project. I think that was the intention behind #268 ? This project needs to be on Github or GitLab?

**Comment by mssammon** [comment]
@shatu github vs gitlab is up for debate. I'm closing this issue as it is superseded by #268.
