### ISSUE TITLE
Important issue; please read it 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#273]
Hey all, 

(Sorry for spamming!)

We realized many people don't ignore their github notifications, due to high volume of emails that they receive. 
If that's the case for you, go to [the main project page](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp), and set the project notification to "not watching": 

<img width="1215" alt="screen shot 2016-11-11 at 2 19 18 pm" src="https://cloud.githubusercontent.com/assets/2441454/20229040/edede94a-a819-11e6-8ec1-6bec5a78d0a9.png">

This way you will receive notifications only if you are mentioned with `@` operator. 

@b29308188
@cgraber
@ChaseDuncan
@cowchipkid
@haowu4
@hhuang97
@Kevin5025
@lingss0918
@mayhewsw
@mliu-dark-knight
@mpavankumarreddy
@mssammon
@nitishgupta
@penghaoruo
@qiangning
@sdan2
@shatu
@Shivam2501
@snigdhac
@tkao1000
@yqsong
@yxd126
@shyamupa
@bhargav 

** If you read this and fixed your notification setting please comment below **

**Comment by bhargav** [comment]
Update my notification setting. 💯

**Comment by mayhewsw** [comment]
Second.

**Comment by shatu** [comment]
Aye!

**Comment by nitishgupta** [comment]
Done. Thanks!

**Comment by 666666fzl** [comment]
Thanks!

**Comment by qiangning** [comment]
Got it, Daniel.
