### ISSUE TITLE
Moving illinois-quantifier to here? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#277]
Do we want to move the [illinois-quantifier](https://gitlab-beta.engr.illinois.edu/cogcomp/illinois-quantifier) to here?

**Comment by danyaljj** [comment]
I have updated the quantifier package with the latest pipeline etc and deployed its models. Are people cool with moving it here? @mssammon are comments on this?

**Comment by mssammon** [comment]
I'm OK with it.
