### ISSUE TITLE
document gurobi requirement or make it optional

### ISSUE THREAD

**Issue by mssammon** [IllinoisCogComp/illinois-cogcomp-nlp#297]
inference module requires gurobi to be installed, or installation fails. Current documentation does not make this sufficiently clear.  Either document it, or make the dependency optional.

**Comment by danyaljj** [comment]
Should it be clarified in the inference readme?

**Comment by mssammon** [comment]
Both in the inference README and the main project README. The latter because it will cause a failure if you just try to build the illinois-cogcomp-nlp project; I assume many people will not read every module README before trying to use it.

**Comment by danyaljj** [comment]
We can also have a separate document like FAQ (linked from the rood readme) which contains common issues with testing and running the code base. How does that sound?

**Comment by mssammon** [comment]
Good idea -- though we should still briefly mention commonly-encountered issues in the relevant READMEs where we point to the FAQ.

**Comment by danyaljj** [comment]
Closed via #298
