### ISSUE TITLE
SL-dependency parser? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#302]
There is a dependency parser inside SL: https://github.com/IllinoisCogComp/illinois-sl-examples/tree/master/src/main/java/edu/illinois/cs/cogcomp/sl/applications/depparse

Is it good enough/functional to be used inside the pipeline?

**Comment by mssammon** [comment]
No, but @mliu-dark-knight is working on integrating his improved version of this dependency parser as we speak...

**Comment by danyaljj** [comment]
Closing because of #178
