### ISSUE TITLE
Pipeline webservers

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#307]
Makes it accessible over the server via POST and GET request. 
Then we can receive the results with Java, Python, Javascript, etc.

**Comment by mssammon** [comment]
Three possibilities: Spring framework (https://projects.spring.io/spring-framework/ -- Chen-Tse used it in xlwikifier); Swagger (http://swagger.io/); and LAPPS would make our stuff compatible with a different NLP framework (https://www.lappsgrid.org/).  These last two are being used by two of the teams in the LORELEI project.

**Comment by danyaljj** [comment]
Closed with #309
