### ISSUE TITLE
Fix file path problems in IOUtilss

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#31]
Same as: https://github.com/cogcomp-dev/illinois-cogcomp-nlp/issues/171 

IOUtils uses some very hacky methods for deciding if something is a directory or a file. This needs to be updated! Line 311 is especially bad. 

Also, all forward slashes need to be replaced with platform agnostic separators.

illinois-cogcomp-nlp/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/io/IOUtils.java

**Comment by haowu4** [comment]
We should not change "/" to File.separator. Those are Jar entry url, not real file system entry. As a result, they are always seperated by "/".

https://bugs.openjdk.java.net/browse/JDK-6303716

**Comment by mssammon** [comment]
@haowu4 I'm assuming I can close this issue.  Please reopen if I'm incorrect.
