### ISSUE TITLE
How to handle cache collision for two pipeline instances? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#310]
As mentioned in the [FAQ of the pipeline](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/tree/master/pipeline#63-frequently-asked-questions-faqs): 
"Initializing multiple instances of PipelineFactory in a single run will lead to an exception in MapDB."

Here is an issue that it might bring. Say I am using an external tool (say illinois-quantifier, which is not included in the pipeline, but it's using pipeline internally), and I'm using pipeline directly. Since there are two pipelines involved their cache files will clash. Do we have any solutions for that?

**Comment by danyaljj** [comment]
Clearly one solution is to have different names for the cache file of each component. Another solution is to automatically create cache with different name (and show a warning). Or how about using the same cache file simultaneously by multiple pipeline instances? (if that's ever possible)

**Comment by mssammon** [comment]
Right now, the cache is associated with the BasicAnnotatorService, NOT the Annoator.  If you want to use the illinois-quantifier, you can *add* it to the pipeline's AnnotatorService (and its output will be cached just like everything else).  If you instantiate a second pipeline, you could configure it to write to a different cache -- there is a key in the Configurator. So if MapDB throws an exception, it has to be something beyond simply sharing a directory (or there  is a bug in the BasicAnnotatorService implementation).  
Note that these are not currently tested -- we should add a test for each of these cases. 
BTW What is the use case for a second pipeline?

**Comment by danyaljj** [comment]
So I was trying to use pipeline and illinois-quantifier in a  project (both as dependency). Since the quantifier already instantiates a pipeline, I had to open it and change the cache name manually and deploy it, so that I can use it. But I think it must be easier than this, I think ...
