### ISSUE TITLE
Consistent usage of logger everywhere

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#32]
Some places is using Logger to output comments: 
https://github.com/cogcomp-dev/illinois-cogcomp-nlp/blob/master/ner/src/main/java/edu/illinois/cs/cogcomp/ner/IO/ResourceUtilities.java#L15

Suggested to make this consistent all over the library.

**Comment by mssammon** [comment]
Please visit the modules in order and go through the code, checking for debug print statements and replacing them with logger. If you find tests that print() instead of assert()-ing, assess how much work there is. If it's a lot, please open a new ticket indicating which module/tests.

**Comment by mssammon** [comment]
@666666fzl how is this going?
