### ISSUE TITLE
Get token Ids given char offset? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#328]
Do we have a mechanism for retrieving tokenIds which contain a specific char offset?

**Comment by danyaljj** [comment]
Clearly one approach is to look over the constituents and filtering the ones that contain the given char offsets. I wonder if there is a better of doing this.

**Comment by mssammon** [comment]
There is only one tokenID for a given character offset, and there is a method for doing this in TextAnnotation: https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/datastructures/textannotation/TextAnnotation.java#L268
