### ISSUE TITLE
[pipeline] ?

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#386]
@mssammon what's happening in [this line](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/pipeline/src/main/java/edu/illinois/cs/cogcomp/pipeline/main/SentencePipeline.java#L108-L109)?  Why `sentView` is never used?

**Comment by mssammon** [comment]
you don't need the actual variable, just to add the view to the TextAnnotation (which getView() does). We can delete the variable.
