### ISSUE TITLE
edu.illinois.cs.cogcomp.ner build fails

### ISSUE THREAD

**Issue by futurus** [IllinoisCogComp/illinois-cogcomp-nlp#394]
These packages don't exist?
edu.illinois.cs.cogcomp.ner.LbjFeatures.NETaggerLevel1;
edu.illinois.cs.cogcomp.ner.LbjFeatures.NETaggerLevel2;

**Comment by danyaljj** [comment]
They get generated upon running `mvn compile`.

**Comment by futurus** [comment]
Yep that works. Thank you.
