### ISSUE TITLE
Trailing Whitespace in StatefulTokenizer

### ISSUE THREAD

**Issue by cowchipkid** [IllinoisCogComp/illinois-cogcomp-nlp#47]
White space trailing a delineated sentence at the end of a text will result in an array index exception

**Comment by nitishgupta** [comment]
Shouldn't the sentence be 'trimmed' before tokenization?

**Comment by cowchipkid** [comment]
Yes, that is the solution I am implementing.

**Comment by cowchipkid** [comment]
cleaned up the white space, it is now fixed.

**Comment by danyaljj** [comment]
@cowchipkid will you apply the fix on this repo as well?

**Comment by cowchipkid** [comment]
I am now ready to issue a PR for this fix. There were permissions issues, likely because I tried to branch directly off IllinoisCogComp/illinois-cogcomp-nlp it would not let me do that. So I have created a fork, made the change on a branch off of my fork, and I am now going to (try to) issue a PR from that fork back to here.
