### ISSUE TITLE
`Table.toOrgTable` method does not align columns

### ISSUE THREAD

**Issue by bhargav** [IllinoisCogComp/illinois-cogcomp-nlp#49]
Table should have a method to get output with aligned columns.

**Comment by shyamupa** [comment]
I think org table is a specific thing. If you use it with emacs it gets automatically aligned.

**Comment by bhargav** [comment]
Okay. I think we should probably have another method to get a text-only formatted table.

**Comment by danyaljj** [comment]
Closed via #213 (I think).
