### ISSUE TITLE
Change FeatureManifest

### ISSUE THREAD

**Issue by xinbowu2** [IllinoisCogComp/illinois-cogcomp-nlp#55]
Since some features like ParsePhraseType are missed by the feature manifest, one additional line of code has been added to FeatureManifest.java to enable the feature manifest to add missed features.

**Comment by xinbowu2** [comment]
Until now, I do not find this change will affect feature manifest in generating other features.

**Comment by mssammon** [comment]
please create a branch with the change and make a pull request.  Please include your comments above when you make the PR.  Please also add a test that demonstrates the behavior of FeatureManifest you fixed.

**Comment by christos-c** [comment]
@xinbowu2 can you make this into a pull request. If not, add the line you changed here as a comment.

**Comment by xinbowu2** [comment]
Hi Christos,
My repo is very inconsistent now. It seems that the PR will pull all of
staff.
Please see the changed codes in FeatureManifest below.

private List<String> getUniqueList(Tree<String> tree) {
     List<String> f = new ArrayList<>();
   f.add(tree.getLabel());  //Changed line
for (Tree<String> child : tree.getChildren()) {
f.add(child.toString().replaceAll("\\s+", " "));

                      }



2016-05-09 22:36 GMT+08:00 Christos Christodoulopoulos <
notifications@github.com>:

> @xinbowu2 <https://github.com/xinbowu2> can you make this into a pull
> request. If not, add the line you changed here as a comment.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/issues/55#issuecomment-217882390>
>


2016-05-09 22:36 GMT+08:00 Christos Christodoulopoulos <
notifications@github.com>:
