### ISSUE TITLE
Readme has a typo

### ISSUE THREAD

**Issue by paultgibbons** [IllinoisCogComp/illinois-cogcomp-nlp#59]
https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/README.md
Has a typo.
The last line of the section "Using each library programmatically" is missing a right brace in the line
... " need the <repository element for "...

**Comment by nitishgupta** [comment]
Can you change and send a pull request?

**Comment by christos-c** [comment]
Fixed in #62
