### ISSUE TITLE
duplication of ArgumentFeatures?

### ISSUE THREAD

**Issue by mssammon** [IllinoisCogComp/illinois-cogcomp-nlp#87]
...in Edison's SRL verb identifier and classifier packages? they are almost but not exactly the same.

**Comment by xinbowu2** [comment]
Yes,  you are right. They are slightly different according to their definitions.

**Comment by christos-c** [comment]
So maybe we should name them differently?

**Comment by mssammon** [comment]
yes -- they are named differently in the large PR I'm about to make
