### ISSUE TITLE
inconsistent test results

### ISSUE THREAD

**Issue by mssammon** [IllinoisCogComp/illinois-cogcomp-nlp#89]
Not for the first time, we have had different test results for the following tests:
testParsePhraseCharniak(edu.illinois.cs.cogcomp.edison.features.factory.ParsePhraseTypeOnlyTest):
testParsePhraseStanford(edu.illinois.cs.cogcomp.edison.features.factory.ParsePhraseTypeOnlyTest):
testParsePhraseGold(edu.illinois.cs.cogcomp.edison.features.factory.ParsePhraseTypeOnlyTest):
testBinaryExample(edu.illinois.cs.cogcomp.edison.utilities.TestWriteSVMLightFormat)
testMulticlassExample(edu.illinois.cs.cogcomp.edison.utilities.TestWriteSVMLightFormat):

Ubuntu/mac has one set of results, and scientific linux has another (clean install on woodhouse). The tests seem like they should be deterministic.

**Comment by cogcomp-dev** [comment]
duplicates #151 and #152
