### ISSUE TITLE
Broken link to illinois-core-utilities in the Readme

### ISSUE THREAD

**Issue by ksuderman** [IllinoisCogComp/illinois-cogcomp-nlp#95]
The link to the core-utilities module on the first line of the README.md file is broken.  I suspect this is a simple typo in the link text.

**Comment by mayhewsw** [comment]
Thanks for the tip. Do you mean [this file](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/README.md)? The link works for me.

**Comment by ksuderman** [comment]
Sorry, I should have been more specific; I thought this was an Edison specific issue-tracker.  It is the README.md file in the Edison directory.  Specifically https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/edison/README.md

**Comment by mayhewsw** [comment]
Fixed and merged. Thanks again for the tip.

**Comment by danyaljj** [comment]
Thanks; should be fixed now ...
